# Generated by Django 5.0.6 on 2024-05-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubedirectorypage',
            name='featured_videos',
        ),
    ]
