# Generated by Django 5.0.6 on 2024-05-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_youtubevideopage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideopage',
            name='disable_kb',
        ),
        migrations.RemoveField(
            model_name='youtubevideopage',
            name='enable_js_api',
        ),
        migrations.RemoveField(
            model_name='youtubevideopage',
            name='origin',
        ),
        migrations.AddField(
            model_name='youtubedirectorypage',
            name='disable_kb',
            field=models.BooleanField(blank=True, default=False, help_text='Causes the player to not respond to keyboard controls.'),
        ),
        migrations.AddField(
            model_name='youtubedirectorypage',
            name='enable_js_api',
            field=models.BooleanField(blank=True, default=False, help_text='Enables the player to be controlled via iFrame Player API calls.'),
        ),
        migrations.AddField(
            model_name='youtubedirectorypage',
            name='origin',
            field=models.URLField(blank=True, help_text='The domain of the website that will be allowed to embed the player. Required by enable_js_api.'),
        ),
    ]
