runtime: python311
instance_class: F4

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: 'cattube_headless.settings.production'
